In [20]:

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(sys.path[0])))

#print(sys.path)

from framework import dataset_mgr 
from framework.dataset_mgr import draw_umich_gaussian
from framework.dataset_mgr import gaussian2D
from IPython.display import display
from PIL import Image
import numpy as np
mat = np.ones((50, 50, 3),dtype=np.uint8)
#print(mat.shape)
#display(Image.fromarray(mat))
if 1:
    #mat = mat * 128
    #print(mat.shape)
    x = gaussian2D((10,10))* 255
    x = x.astype(np.uint8)
    print(x.shape)
    print(x)
    #x = np.expand_dims(x, axis=2)
    #print(x)

    mat[10:10+x.shape[0], 10:10+x.shape[1],[0,1,2]] = x
    #mat[10:10+x.shape[0], 10:10+x.shape[1],1] = x
    #mat[10:10+x.shape[0], 10:10+x.shape[1],2] = x


    print((mat == 0).all())
    display(Image.fromarray(mat))

m: 4.5, n: 4.5
y: [[-4.5]
 [-3.5]
 [-2.5]
 [-1.5]
 [-0.5]
 [ 0.5]
 [ 1.5]
 [ 2.5]
 [ 3.5]
 [ 4.5]] with shape: (10, 1), x:[[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]], with shape: (1, 10)
all larger than 0 True
gaussian max is:  0.7788007830714049
filter not working? True
(10, 10)
[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   3   9   9   3   0   0   0]
 [  0   0   3  26  73  73  26   3   0   0]
 [  0   0   9  73 198 198  73   9   0   0]
 [  0   0   9  73 198 198  73   9   0   0]
 [  0   0   3  26  73  73  26   3   0   0]
 [  0   0   0   3   9   9   3   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]]


ValueError: shape mismatch: value array of shape (10,10) could not be broadcast to indexing result of shape (10,10,3)